# Generated by Django 6.0 on 2026-01-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, upload_to='recipes/cover/%Y/%m/%d/'),
        ),
    ]
